title: Hi! I'm Ashlee Tiwari
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "/ashleetiw" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ashlee Tiwari # add your name
author-img: me.png # add your photo
about-author: I am eager to learn new domains and enjoy building solutions to challenging problems. Education:Northwestern University | IIT Kanpur  # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: ashleetiw # add your Github handle
social-linkedin: ashleetiwari # add your Linkedin handle
social-email: ashleetiwari2021@u.northwestern.edu # add your Email address

# Disqus
# discus-identifier: m # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
